### ISSUE TITLE
Crash when running against PDB

### ISSUE THREAD

**Issue by SourceCodeDeleted** [mstange/pdb-addr2line#52]
Hello when running the following, I receive 

`~/symbols$ pdb-addr2line --exe a/PdbProject.pdb  0x0412483`

```

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/pdb-addr2line-0.7.1/examples/pdb-addr2line.rs:242:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It works for your example , but not for this one it seems. Is  my PDB too old or does this only work for x64 binaries or something?

Is there something we can do about this, or is this project not really supported any more?

**Comment by mstange** [comment]
It's panicking on this line:

https://github.com/mstange/pdb-addr2line/blob/a2a938f8b9745462618c1318a032c498510319f7/examples/pdb-addr2line.rs#L242

This could clearly use some error handling and print a message that no symbols were found at that address.

But if you were expecting symbols to be present at this address, then there's probably some bug or unhandled case in pdb-addr2line and I'd like to make it work. Maybe the pdb doesn't have "section contribution" information.

> Is there something we can do about this, or is this project not really supported any more?

It is very much supported and in active use. It just hasn't needed any changes recently because it's working very well for my use case. And also because the project doesn't seem to have many users yet.

**Comment by mstange** [comment]
Yes, please.

**Comment by SourceCodeDeleted** [comment]
[richheader_check.zip](https://github.com/mstange/pdb-addr2line/files/8718164/richheader_check.zip)

**Comment by mstange** [comment]
Thank you, this is super useful, especially in combination with the symbolsdump.txt.

It looks like this PDB is the outcome of a `/DEBUG:FASTLINK` link step:

```
(000048) S_ENVBLOCK:
         Compiled for edit and continue: no
         Command block:
          cwd = 'C:\Users\krash\source\repos\richheader_check\richheader_check'
          exe = 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x86\link.exe'
          pdb = 'C:\Users\krash\source\repos\richheader_check\Debug\richheader_check.pdb'
          cmd = ' /ERRORREPORT:PROMPT /OUT:C:\Users\krash\source\repos\richheader_check\Debug\richheader_check.exe /INCREMENTAL /NOLOGO /LIBPATH:C:\Users\krash\Desktop\devilutionX-master\vcpkg\installed\x86-windows\debug\lib /LIBPATH:C:\Users\krash\Desktop\devilutionX-master\vcpkg\installed\x86-windows\debug\lib\manual-link /MANIFEST "/MANIFESTUAC:level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:C:\Users\krash\source\repos\richheader_check\Debug\richheader_check.pdb /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:C:\Users\krash\source\repos\richheader_check\Debug\richheader_check.lib /MACHINE:X86'
```

Here's what [the Microsoft docs](https://docs.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=msvc-170) have to say about this option:

> The /DEBUG:FASTLINK option is available in Visual Studio 2017 and later. This option leaves private symbol information in the individual compilation products used to build the executable. It generates a limited PDB that indexes into the debug information in the object files and libraries used to build the executable instead of making a full copy. This option can link from two to four times as fast as full PDB generation, and is recommended when you are debugging locally and have the build products available. This limited PDB can't be used for debugging when the required build products are not available, such as when the executable is deployed on another computer. In a developer command prompt, you can use the mspdbcmf.exe tool to generate a full PDB from this limited PDB. In Visual Studio, use the Project or Build menu items for generating a full PDB file to create a full PDB for the project or solution.

Your fastest way to a PDB file which works with pdb-addr2line is probably to follow those instructions at the end and configure MSVC to output a full PDB file.

However, there are definitely a few things I can fix within pdb-addr2line, because the PDB file does contain some information: It contains public symbols, and it also has some line information in some of the modules. For example it has this:

```
  C:\Users\krash\source\repos\richheader_check\richheader_check\main.cpp (MD5: A1F59A8FE104BFB78DBC0D10AF6CD976), 0002:0000FB60-0000FE29, line/addr pairs = 47

     51 0000FB60  f00f00 0000FB7E     52 0000FB88     54 0000FB8F
     57 0000FC51     58 0000FC58     60 0000FC5D     61 0000FC64
     63 0000FC69     64 0000FC70     66 0000FC75     67 0000FC7C
     69 0000FC81     70 0000FC88     72 0000FC8D     73 0000FC94
     75 0000FC99     76 0000FCA0     78 0000FCA2     79 0000FCA9
     81 0000FCAB     82 0000FCB2     84 0000FCB4     85 0000FCBB
     87 0000FCBD     88 0000FCC4     90 0000FCC6     91 0000FCCD
     93 0000FCCF     94 0000FCD6     96 0000FCD8     97 0000FCDF
     99 0000FCE1    100 0000FCE8    102 0000FCEA    103 0000FCF1
    105 0000FCF3    106 0000FCFA    108 0000FCFC    109 0000FD03
    111 0000FD05    112 0000FD0C    114 0000FD0E    115 0000FD15
    117 0000FD17    120 0000FD1E    121 0000FD21

  C:\Users\krash\source\repos\richheader_check\richheader_check\main.cpp (MD5: A1F59A8FE104BFB78DBC0D10AF6CD976), 0002:0000FEE0-00010A4F, line/addr pairs = 59

    158 0000FEE0  f00f00 0000FF20    159 0000FF2A    160 0000FF56
    162 0000FF7C    163 0000FFB3    166 0000FFCA    169 00010001
    170 0001002B    172 0001003D    173 00010066    174 000100BF
    179 000100D6    180 00010100    181 0001012A    183 00010136
    185 00010187    190 0001019E    191 000101C8    192 000101F2
    194 00010207    196 00010258    199 0001026F    200 0001029E
    202 000102AA    204 00010310    208 00010327    212 00010393
    215 000103A8    217 000103B3    220 000103CB    222 000103FB
    227 0001042C    228 0001043B    230 000104E9    231 00010538
    233 00010544    234 000105A3    236 000105A5    237 000105AA
    239 000105CC    240 000105F5    243 0001060C    247 0001065B
    248 0001066A    250 00010718    251 0001076D    253 00010779
    254 000107C1    256 000107C3    257 000107C8    259 000107EA
    260 00010813    262 0001082A    264 00010839    266 0001088A
    268 000108E7    274 000108FE    275 0001098C
```

So, while you won't get any information for inlines, I think we can get at least some function names and filename + line information.

**Comment by mstange** [comment]
To do:

 - [ ] In the list of global symbols, include synthetic "placeholder" symbols. Generate one placeholder symbol for each section contribution, before merging adjacent section contributions.
 - [ ] Support looking up file + line information for public / placeholder symbols as well, not just for procedure symbols.
 - [ ] Print a better error in the example if address lookup failed

**Comment by mstange** [comment]
In this file, we should get the following results:

0x18258 should give `std::exchange<std::_Tree_node<...>*, std::nullptr_t>(...)` at `include\utility:603`
0x258A3 should give `std::ios_base::good(void) ` without file or line info
0x2202D should give "unknown function" at `richheader_check\main.cpp:288`, and *not* `std::basic_string[...]`

**Comment by mstange** [comment]
Ok, I've fixed everything that's within reach. I'll file a new issue for proper `/DEBUG:FASTLINK` support. We would need to get the file names to the supplemental files, read those files, and integrate the information somehow. It doesn't look like there's a lot of public information about this format yet, and the pdb crate does not support the relevant symbols yet.

**Comment by mstange** [comment]
@SourceCodeDeleted I'd like to add the two files you uploaded into this repository so that I can write some tests based on them. Is that ok with you? I'm asking for permission because the files contain some absolute paths with your Windows username in them.

**Comment by SourceCodeDeleted** [comment]
yes that is perfectly fine with me . Thank you )

**Comment by mstange** [comment]
Great, thanks!
