### ISSUE TITLE
Question: possible to extract the base address from pdb ?

### ISSUE THREAD

**Issue by SourceCodeDeleted** [mstange/pdb-addr2line#54]
I wanted to ask is it possible to extract the base address from these pdb files ?

**Comment by mstange** [comment]
I haven't come across the base address in the pdb data structures I've been looking at. So my guess is no.

But if you have the exe / dll, you can get the base address from those, for example using [`Object::relative_address_base`](https://docs.rs/object/0.28.4/object/read/trait.Object.html#tymethod.relative_address_base).
