### ISSUE TITLE
Get function name without arguments

### ISSUE THREAD

**Issue by Scui1** [mstange/pdb-addr2line#58]
Hi, is there any easy way to get only the functions name without all of the arguments?
Would I have to write my own implementation of `TypeFormatter`? Please bear with me, I just started with rust...

**Comment by mstange** [comment]
Oh, huh, I was going to point you to [`ContextPdbData::make_type_formatter_with_flags`](https://docs.rs/pdb-addr2line/0.10.2/pdb_addr2line/struct.ContextPdbData.html#method.make_type_formatter_with_flags) and then show you the [`TypeFormatterFlags`](https://docs.rs/pdb-addr2line/0.10.2/pdb_addr2line/struct.TypeFormatterFlags.html) for eliminating function arguments... but it looks like there is no `NO_ARGUMENTS` flag!

I will add one.

**Comment by Scui1** [comment]
I was bored and need to improve my rust knowledge anyways, so I created a pr that adds the wanted functionality. #59

**Comment by mstange** [comment]
I've released 0.10.3 with the fix.
